language: r
sudo: required

install:
  - sudo Rscript -e "install.packages('knitr', repos = c('http://yihui.name/xran', 'http://cran.rstudio.org'),  type = 'source')"
  
script:
  - sudo Rscript -e "library(knitr); knit('ejemplo.Rmd')" 
  - sudo Rscript -e "library(knitr); knit('ejemplo2.Rmd')" 
