language: r
R:
  - "3.0.2"
  
  
  
# command to run tests
script: 
  - sudo Rscript -e "library(knitr); knit('ejemplo.Rmd')" 
  - sudo Rscript -e "library(knitr); knit('ejemplo2.Rmd')"



  
  






