language: r
R:
  - "3.0.2"

  
# command to install dependencies
install: 
  - sudo apt-get update -qq
  - sudo sh -c 'echo "deb http://ftp.iitm.ac.in/cran/bin/linux/ubuntu trusty/" >> /etc/apt/sources.list'
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
  - sudo add-apt-repository -y ppa:marutter/rdev
  - sudo apt-get -y install r-base 
  - sudo apt-get -y install r-base-dev
  - sudo wget https://cran.r-project.org/src/contrib/knitr_1.11.tar.gz
  - sudo R CMD INSTALL knitr_1.11.tar.gz



  
# command to run tests
script: 
  - sudo Rscript -e "R.version"
  - sudo Rscript -e "library(knitr); knit('ejemplo.Rmd')"

  
  






