language: r

  
# command to install dependencies
install: 
  - sudo Rscript -e "install.packages('knitr', repos = c('http://yihui.name/xran', 'http://cran.rstudio.org'), type = 'source')"



  
# command to run tests
script: 
  - sudo Rscript -e "R.version"
  - sudo Rscript -e "library(knitr); knit('ejemplo.Rmd')"

after_script:
  - ls


  
  






