language: r

  
# command to install depende
  - sudo install.packages('knitr', repos = c('http://yihui.name/xran', 'http://cran.rstudio.org'),  type = 'source')

  
# command to run tests
script: 
  - sudo Rscript -e "library(knitr); knit('ejemplo.Rmd')" 
  - sudo Rscript -e "library(knitr); knit('ejemplo2.Rmd')"



  
  






