language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  
  
environment:
  access_token:
    secure: 4d31105ed60db6c965982c7f4d0484627be7807f


# command to install dependencies
install: 
  - sudo apt-get update -qq
  - sudo apt-get install python
  - sudo apt-get install python-pip python-dev build-essential
  - sudo pip install --upgrade pip
  - sudo pip install --upgrade virtualenv
  - sudo pip install -U pip
  - sudo python ez_setup.py
  - sudo pip install --upgrade Pweave
  - sudo apt-get install python-matplotlib
# command to run tests
script: 
  - Pweave -f pandoc ejemplo2.Pnw
  - Pweave -f pandoc ejemplo3.Pnw

#Después de que lo convierta
after_script: 
  - git config --global user.email "arturoinosencio@gmail.com"
  - git config --global user.name "Wowip"
  - git config --global credential.helper store
  - ps: Add-Content "$env:Wowip\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
  - git init
  - ls
  - git add .
  - git pull
  - git commit -m "Añadiendo ejemplo2.md"
  - git push origin master
  


env:
  global:
    secure: {"lots-of-seemingly-random-characters"}
