language: r
R:
  - "3.0.2"

  
# command to install dependencies
install: 
  - sudo apt-get update -qq
  - sudo Rscript -e "install.packages('knitr', repos = c('http://yihui.name/xran', 'http://cran.rstudio.org'), type = 'source')"



  
# command to run tests
script: 
  - sudo Rscript -e "R.version"
  - sudo Rscript -e "library(knitr); knit('ejemplo.Rmd')"

  
  






